### PR TITLE
condition template selection page

### LINKED ISSUE #75: Build in condition template selection page
Designs: [Condition template selection page](https://www.figma.com/design/Iuw9me6kYftBF4WTCEsCZz/Query-Connector?node-id=475-18708&t=nCvdKQwvRKVyZnv4-4)

## Acceptance Criteria

Ability to

*  Add the query name in the text box, which should save on creation
* Search conditions, which should act like a filter / update automatically on character input
* Select the condition templates you want to start with
* Hit create query when done
  * Create query button is disabled until at least one template is selected

### PR DESCRIPTION
**Pull request by fzhao99**
# PULL REQUEST

## Summary
Part two that builds the actual page.

For now, I've put this page at `/queryBuilding/buildFromTemplate`, but worth a larger convo around when we use the Next router for URL-based rendering and when we handle things in a more SPA fashion like we do with the query search flow.

### For design
- Page available at `queryBuilding/buildFromTemplate`. The page is read-only for now (ie the "create query" button doesn't do / redirect to anything and the query name field also doesn't do anything). "Writing" this info and updating the relevant pages are forthcoming
- Check that spacing, font, colors are aligned with design
     - Recognize the two columns are unbalanced in terms of how many conditions are in the two columns, but balancing them is an instance of [the knapsack problem](https://developers.google.com/optimization/pack/knapsack#:~:text=In%20the%20knapsack%20problem%2C%20you,can't%20pack%20them%20all.). Basically, the algorithm to do is really complicated, which felt like overkill for the context.
     - Can revisit this in a followup PR though! Might be fun to dust off my actual computer science degree :) 
- Check the interactivity for the search field
- The "Create Query" button is disabled for now until at least one template is selected, but will leave us to update the interaction based on [this conversation.](https://skylight-hq.slack.com/archives/C07PQ078KK2/p1730997768181319) in another PR

## Related Issue
Fixes #75

## Checklist
- [x] Descriptive Pull Request title
- [x] Link to relevant issues
- [x] Provide necessary context for design reviewers
- [x] Update documentation

### CODE REVIEW

**Review by robertandremitchell — APPROVED** [review]
looks good to me. only minor quibbles
* at least on the figma Back to My Queries isn't underlined
* there isn't the Demo alert at the top of the page. that might be just because the page is not connected to stuff currently, as i write this..carry on!

**Comment by mikang** [comment]
The search is beautiful @fzhao99 — I think it deserves its own GH comment

**Comment by mikang** [comment]
Here is my feedback! https://docs.google.com/document/d/1gMX9AMwk1KAnuN2e8_cvlaMg1kbNQOac86mE5cBVg28/edit?usp=sharing

**Comment by mikang** [comment]
> looks good to me. only minor quibbles
> 
> * at least on the figma Back to My Queries isn't underlined
> * there isn't the Demo alert at the top of the page. that might be just because the page is not connected to stuff currently, as i write this..carry on!

hmm true about the underline. I didn't notice that on the other pages. Is it possible to remove the underline from all backlinks that have an arrow? The underline is good for accessibility to show that it's clickable, but considering there is an arrow, I'm not concerned about it not seeming clickable

**Pull request merged**
