### PR TITLE
Query Updating Concept Selection 

### LINKED ISSUE #140: Implement query updating on concept selection
## Description:

Based on the determination from [QUE-70](https://linear.app/skylight-cdc/issue/QUE-70/spike-when-how-to-do-the-valueset-update-to-the-backend), implement the "write" part of the slide over

## Acceptance Criteria:

* A user can select and save individual concepts from the query building concept selection flow

### PR DESCRIPTION
**Pull request by robertandremitchell**
# PULL REQUEST

## Summary

This finishes the frontend implementation of the Drawer component for the View Codes concept workflow . It adds:
* A dynamic pulling of the concept code and name to display when view codes is clicked
* A super-checkbox for the entire valueset
* Checkboxes for each of the concepts
* A Save Changes button that is disabled until a change from the status quo is detected
* A warning Modal if there are changes to ask if the changes should be saved or dismissed

Screenshot 2024-12-19 at 8 54 29 AM
Screenshot 2024-12-19 at 8 54 40 AM
Screenshot 2024-12-19 at 8 54 46 AM
Screenshot 2024-12-19 at 8 54 55 AM
Screenshot 2024-12-19 at 8 55 10 AM

## Related Issue

Fixes #140

## Additional Information

I'm having some trouble writing the code to get the changes to "stick". I.e., if there are six concepts, we remove one, we should see `5/6` for the valueset. I have not yet been able to get this work / the changes to truly save on a concept-by-concept level. Gonna keep hacking at it this morning.

Happy to pair on it, or tackle it as part of a larger ticket on getting every part of the page to save, as that is currently nonfunctional cc @fzhao99.

@mikang , I am curious if we want a the Minus checkbox in the concept workflow? I.e., if one of six concepts is deselected, the super-checkbox would display the minus-sign checkbox. Right now, in the designs, the checkbox is still selected, which I guess kinda makes sense given that we are still included 1 whole valueset, just with concepts missing. But I wasn't sure. As always, if there are any other frontend display changes/copy to modify/add lmk!

Anything else the review team should know?

## Checklist

- [ ] Descriptive Pull Request title
- [ ] Link to relevant issues
- [ ] Provide necessary context for design reviewers
- [ ] Update documentation

### CODE REVIEW

**Comment by mikang** [comment]
Yes! Great catch. Let's do the minus sign! Thank you @robertandremitchell 

also, hey, the modal looks great!!

**Comment by robertandremitchell** [comment]
> Yes! Great catch. Let's do the minus sign! Thank you @robertandremitchell
> 
> also, hey, the modal looks great!!

added!

**Comment by fzhao99** [comment]
going to put this back in draft to figure out some UI updating issues on monday

**Comment by fzhao99** [comment]
closing in favor of https://github.com/CDCgov/dibbs-query-connector/pull/232

**Pull request closed without merging**
